### PR TITLE
Solve LocationFormatter Bug

### LINKED ISSUE #105: Location dependent formatting in `LocationFormatter`
The number format of the `LocationFormatter` depends on the current Java local.
```
java.lang.AssertionError: expected [24°59'15.486"N] but found [24°59'15,486"N]
Expected :24°59'15.486"N
Actual   :24°59'15,486"N
``` 
Make the number format independet on the current local.

### PR DESCRIPTION
**Pull request by Segelzwerg**
FIXES #105 

I think I solved it. I'm sure because all tests worked if I set the symbols to
```
Locale.GERMAN
```

Is there a test already implemented for your bug?

I hope I'm more useful than harmful ;)

### CODE REVIEW

**Comment by jenetics** [comment]
You have to fix all `DecimalFormat` creations. This class is used in the `LocationFormatter` and `LocationFieldFormatter` class. You only fixed it in the `LocationFormatter` class on one occurrence. But the `DecimalFormat` class is also created at `LocationFormatter:519`.

**Comment by Segelzwerg** [comment]
> You have to fix all `DecimalFormat` creations. This class is used in the `LocationFormatter` and `LocationFieldFormatter` class. You only fixed it in the `LocationFormatter` class on one occurrence. But the `DecimalFormat` class is also created at `LocationFormatter:519`.

Sorry I missed that one. I was manually searching. Next time I will use CTRL+F first.

**Comment by jenetics** [comment]
Do you think it is possible to have a unit test for this fix? Would be great!

**Comment by Segelzwerg** [comment]
yes I think so, I tried some thing on another project by hand. So it should work out as Unit Test, I think.
I can try something later.

**Comment by Segelzwerg** [comment]
I made two test for both uses of `DecimalFormatSymbols`. I'm not very used to TestNG so my code is a bit bulky, but you can easily check they work by replacing `DecimalFormatSymbols.getInstance(Locale.US);` with `DecimalFormatSymbols.getInstance(Locale.GERMANY);` at `LocationFormatter:514` and `LocationFormatter:711`.

**Pull request merged**
